// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDKJJl33VIxc-imEclITI2qHUY_cqTJZw',
    appId: '1:943695418482:web:0fb9e79dd115d321359eeb',
    messagingSenderId: '943695418482',
    projectId: 'safevoice-85790',
    authDomain: 'safevoice-85790.firebaseapp.com',
    storageBucket: 'safevoice-85790.firebasestorage.app',
    measurementId: 'G-868YCSZ130',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTktZx6UIMoqL8Wi9nFohnanuR3Cp7zzM',
    appId: '1:943695418482:android:0ff23a5ff272f3d6359eeb',
    messagingSenderId: '943695418482',
    projectId: 'safevoice-85790',
    storageBucket: 'safevoice-85790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSneN-7tBpBEHSiNenUP84BjXH5YExTyc',
    appId: '1:943695418482:ios:64d4a1665f18927e359eeb',
    messagingSenderId: '943695418482',
    projectId: 'safevoice-85790',
    storageBucket: 'safevoice-85790.firebasestorage.app',
    iosBundleId: 'com.example.safeVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSneN-7tBpBEHSiNenUP84BjXH5YExTyc',
    appId: '1:943695418482:ios:64d4a1665f18927e359eeb',
    messagingSenderId: '943695418482',
    projectId: 'safevoice-85790',
    storageBucket: 'safevoice-85790.firebasestorage.app',
    iosBundleId: 'com.example.safeVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDKJJl33VIxc-imEclITI2qHUY_cqTJZw',
    appId: '1:943695418482:web:d6be4492b777f04c359eeb',
    messagingSenderId: '943695418482',
    projectId: 'safevoice-85790',
    authDomain: 'safevoice-85790.firebaseapp.com',
    storageBucket: 'safevoice-85790.firebasestorage.app',
    measurementId: 'G-CXM73EC7QW',
  );
}
